name: PythonIntroEnv

channels:
  - conda-forge
  - defaults

dependencies:
    - python>=3.8.*
    - pip>=20.*
    - jupyter
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - plotnine
    - openpyxl
    - cython
    - numba
